[remote.github]
owner = "ajiho"
repo = "releaset-it-demo"

[changelog]
header = """
[![animation](https://raw.githubusercontent.com/ajiho/releaset-it-demo/main/New-Year.gif)](https://git-cliff.org)\n
"""
body = """
{# å®šä¹‰è¿œç¨‹ä»“åº“ URL å® #}
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{# å®šä¹‰æ‰“å° commit çš„å® #}
{% macro print_commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
        {% if commit.breaking %}[**breaking**] {% endif %}\
        {{ commit.message | upper_first }} - \
        ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))\
{% endmacro -%}

{# ç‰ˆæœ¬æ ‡é¢˜ #}
{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]\
          ({{ self::remote_url() }}/compare/{{ previous.version }}..{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\

{# æŒ‰ commit group åˆ†ç»„è¾“å‡º #}
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor %}
    {% for commit in commits %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor -%}
{%- if github and github.contributors | length > 0 -%}

## ğŸ¤ Contributors

{% for contributor in github.contributors %}
- @{{ contributor.username }}
{% endfor -%}

{%- endif -%}

{# æ–°è´¡çŒ®è€…åˆ—è¡¨ï¼ˆåªåˆ—é¦–æ¬¡è´¡çŒ®è€…ï¼‰ #}
{%- if github and github.contributors | filter(attribute="is_first_time", value=true) | length > 0 -%}
## â¤ï¸ New Contributors
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
- @{{ contributor.username }}
  {%- if contributor.pr_number %} in [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}){% endif %}
{% endfor %}
{%- endif -%}
"""

trim = true

[git]
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->ğŸš€  æ–°ç‰¹æ€§" },
    { message = "^fix", group = "<!-- 1 -->ğŸ› Bug ä¿®å¤" },
    { message = "^doc", group = "<!-- 3 -->ğŸ“š æ–‡æ¡£" },
    { message = "^perf", group = "<!-- 4 -->âš¡ æ€§èƒ½ä¼˜åŒ–" },
    { message = "^refactor\\(clippy\\)", skip = true },
    { message = "^refactor", group = "<!-- 2 -->ğŸšœ é‡æ„" },
    { message = "^style", group = "<!-- 5 -->ğŸ¨ æ ·å¼" },
    { message = "^test", group = "<!-- 6 -->ğŸ§ª æµ‹è¯•" },
    { message = "^chore: release v", skip = true },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore\\(npm\\).*yarn\\.lock", skip = true },
    { message = "^chore|^ci", group = "<!-- 7 -->âš™ï¸ æ‚é¡¹ä»»åŠ¡" },
    { body = ".*security", group = "<!-- 8 -->ğŸ›¡ï¸ å®‰å…¨" },
    { message = "^revert", group = "<!-- 9 -->â—€ï¸ å›æ»š" },
]
